const GET = 'get'
const POST = 'post'
const PUT = 'put'
const DELETE = 'delete'
const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
const REQUEST_CANCELLED_ERROR = 'REQUEST_CANCELLED_ERROR'
const REQUEST_CONNECTION_ERROR = 'REQUEST_CONNECTION_ERROR'
const UNEXPECTED_RUNTIME_ERROR = 'UNEXPECTED_RUNTIME_ERROR'
const UNEXPECTED_SERVER_ERROR = 'UNEXPECTED_SERVER_ERROR'

export {
  GET,
  POST,
  PUT,
  DELETE,
  INTERNAL_SERVER_ERROR,
  REQUEST_CANCELLED_ERROR,
  REQUEST_CONNECTION_ERROR,
  UNEXPECTED_RUNTIME_ERROR,
  UNEXPECTED_SERVER_ERROR,
}